<?php
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Controllers;

use PersonalCloudStorageAPIsLib\APIException;
use PersonalCloudStorageAPIsLib\APIHelper;
use PersonalCloudStorageAPIsLib\Configuration;
use PersonalCloudStorageAPIsLib\Models;
use PersonalCloudStorageAPIsLib\Exceptions;
use PersonalCloudStorageAPIsLib\Http\HttpRequest;
use PersonalCloudStorageAPIsLib\Http\HttpResponse;
use PersonalCloudStorageAPIsLib\Http\HttpMethod;
use PersonalCloudStorageAPIsLib\Http\HttpContext;
use Unirest\Request;

/**
 * @todo Add a general description for this controller.
 */
class ContactsController extends BaseController {

    /**
     * @var ContactsController The reference to *Singleton* instance of this class
     */
    private static $instance;
    
    /**
     * Returns the *Singleton* instance of this class.
     * @return ContactsController The *Singleton* instance.
     */
    public static function getInstance()
    {
        if (null === static::$instance) {
            static::$instance = new static();
        }
        
        return static::$instance;
    }

    /**
     * Retrieves all contacts.
     * @return mixed response from the API call
     * @throws APIException Thrown if API call fails
     */
    public function getContacts () 
    {
        //the base uri for api requests
        $_queryBuilder = Configuration::$BASEURI;
        
        //prepare query string for API call
        $_queryBuilder = $_queryBuilder.'/contacts';

        //validate and preprocess url
        $_queryUrl = APIHelper::cleanUrl($_queryBuilder);

        //prepare headers
        $_headers = array (
            'user-agent'    => 'APIMATIC 2.0',
            'Accept'        => 'application/json',
            'Authorization' => sprintf('Bearer %1$s', Configuration::$oAuthAccessToken)
        );

        //call on-before Http callback
        $_httpRequest = new HttpRequest(HttpMethod::GET, $_headers, $_queryUrl);
        if($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);            
        }

        //and invoke the API call request to fetch the response
        $response = Request::get($_queryUrl, $_headers);

        //call on-after Http callback
        if($this->getHttpCallBack() != null) {
            $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
            $_httpContext = new HttpContext($_httpRequest, $_httpResponse);
            
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);            
        }

        //Error handling using HTTP status codes
        if ($response->code == 401) {
            throw new Exceptions\ErrorResponseException('[Unauthorized] Bearer token is missing, expired, or invalid.', $_httpContext);
        }

        else if ($response->code == 500) {
            throw new Exceptions\ErrorResponseException('Unexpected Account configuration.', $_httpContext);
        }

        else if ($response->code == 503) {
            throw new Exceptions\ErrorResponseException('[Service Unavailable] See response body for more detail.', $_httpContext);
        }

        else if (($response->code < 200) || ($response->code > 208)) { //[200,208] = HTTP OK
            throw new APIException("HTTP Response Not OK", $_httpContext);
        }

        $mapper = $this->getJsonMapper();

        return $mapper->map($response->body, new Models\Contacts());
    }
        

}