<?php
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Exceptions;

use PersonalCloudStorageAPIsLib\APIException;
use PersonalCloudStorageAPIsLib\APIHelper;
/**
 * @todo Write general description for this model
 */
class ErrorResponseException extends APIException{
    /**
     * A unique code identifying the error
     * @required
     * @maps error_code
     * @var string $errorCode public property
     */
    public $errorCode;

    /**
     * A detailed description of the error
     * @required
     * @maps error_description
     * @var string $errorDescription public property
     */
    public $errorDescription;


    /**
    * Constructor to set initial or default values of member properties 
    */
    public function __construct($reason,$context)
    {
        parent::__construct($reason,$context);
    }

    public function unbox()
    {
        $data = APIHelper::deserialize(self::getResponseBody());
        $errorCode = $data['error_code'];
        $errorDescription = $data['error_description'];
    }
}