<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AccountResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var Usage $usage public property
     */
    public $usage;

    /**
     * The user identifier.
     * @var string $id public property
     */
    public $id;

    /**
     * Constructor to set initial or default values of member properties
     * @param   Usage             $usage   Initialization value for the property $this->usage
     * @param   string            $id      Initialization value for the property $this->id   
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->usage = func_get_arg(0);
            $this->id    = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['usage'] = $this->usage;
        $json['id']    = $this->id;

        return $json;
    }
}