<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class BaseFolderMetadata implements JsonSerializable {
    /**
     * The name of the folder
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The name of the folder's parent folder
     * @required
     * @var string $parentPath public property
     */
    public $parentPath;

    /**
     * The size of the folder, in bytes
     * @required
     * @var integer $size public property
     */
    public $size;

    /**
     * Folder version.  This number increases when the folder content changes
     * @required
     * @var integer $version public property
     */
    public $version;

    /**
     * Creation timestamp for the folder's current version, in ISO-8601 format
     * @required
     * @var string $versionCreated public property
     */
    public $versionCreated;

    /**
     * The number of items the folder contains
     * @required
     * @var integer $count public property
     */
    public $count;

    /**
     * If true, the folder has been logically deleted
     * @required
     * @var bool $deleted public property
     */
    public $deleted;

    /**
     * Array of viewUid
     * @required
     * @var ViewUid[] $viewUid public property
     */
    public $viewUid;

    /**
     * Unique identifier of the resource
     * @required
     * @var string $uri public property
     */
    public $uri;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name             Initialization value for the property $this->name          
     * @param   string            $parentPath       Initialization value for the property $this->parentPath    
     * @param   integer           $size             Initialization value for the property $this->size          
     * @param   integer           $version          Initialization value for the property $this->version       
     * @param   string            $versionCreated   Initialization value for the property $this->versionCreated
     * @param   integer           $count            Initialization value for the property $this->count         
     * @param   bool              $deleted          Initialization value for the property $this->deleted       
     * @param   array             $viewUid          Initialization value for the property $this->viewUid       
     * @param   string            $uri              Initialization value for the property $this->uri           
     */
    public function __construct()
    {
        if(9 == func_num_args())
        {
            $this->name           = func_get_arg(0);
            $this->parentPath     = func_get_arg(1);
            $this->size           = func_get_arg(2);
            $this->version        = func_get_arg(3);
            $this->versionCreated = func_get_arg(4);
            $this->count          = func_get_arg(5);
            $this->deleted        = func_get_arg(6);
            $this->viewUid        = func_get_arg(7);
            $this->uri            = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']           = $this->name;
        $json['parentPath']     = $this->parentPath;
        $json['size']           = $this->size;
        $json['version']        = $this->version;
        $json['versionCreated'] = $this->versionCreated;
        $json['count']          = $this->count;
        $json['deleted']        = $this->deleted;
        $json['viewUid']        = $this->viewUid;
        $json['uri']            = $this->uri;

        return $json;
    }
}