<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class BaseFileMetadata implements JsonSerializable {
    /**
     * The name of the file
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The folder where the file is located
     * @required
     * @var string $parentPath public property
     */
    public $parentPath;

    /**
     * The file content's SHA-256 checksum value
     * @required
     * @var string $checksum public property
     */
    public $checksum;

    /**
     * If false, the file content is protected by copywrite and is not accessible to the user
     * @required
     * @var bool $contentAccessible public property
     */
    public $contentAccessible;

    /**
     * A unique string representing the file. Will change if file content is updated.  Required for certain APIs, such as /thumbnails
     * @required
     * @var string $contentToken public property
     */
    public $contentToken;

    /**
     * If true, the file has been logically deleted
     * @required
     * @var bool $deleted public property
     */
    public $deleted;

    /**
     * The file's extension, as extracted from the filename
     * @required
     * @var string $extension public property
     */
    public $extension;

    /**
     * The size of the file, in bytes
     * @required
     * @var integer $size public property
     */
    public $size;

    /**
     * A set of file attributes.  The attribute set will vary depending on file type
     * @required
     * @var object $systemAttributes public property
     */
    public $systemAttributes;

    /**
     * File version.  This number increases when the file is updated
     * @required
     * @var integer $version public property
     */
    public $version;

    /**
     * Creation timestamp for the file's current version, in ISO-8601 format
     * @required
     * @var string $versionCreated public property
     */
    public $versionCreated;

    /**
     * Array of viewUid
     * @required
     * @var ViewUid[] $viewUid public property
     */
    public $viewUid;

    /**
     * Unique identifier of the resource
     * @required
     * @var string $uri public property
     */
    public $uri;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name                Initialization value for the property $this->name             
     * @param   string            $parentPath          Initialization value for the property $this->parentPath       
     * @param   string            $checksum            Initialization value for the property $this->checksum         
     * @param   bool              $contentAccessible   Initialization value for the property $this->contentAccessible
     * @param   string            $contentToken        Initialization value for the property $this->contentToken     
     * @param   bool              $deleted             Initialization value for the property $this->deleted          
     * @param   string            $extension           Initialization value for the property $this->extension        
     * @param   integer           $size                Initialization value for the property $this->size             
     * @param   object            $systemAttributes    Initialization value for the property $this->systemAttributes 
     * @param   integer           $version             Initialization value for the property $this->version          
     * @param   string            $versionCreated      Initialization value for the property $this->versionCreated   
     * @param   array             $viewUid             Initialization value for the property $this->viewUid          
     * @param   string            $uri                 Initialization value for the property $this->uri              
     */
    public function __construct()
    {
        if(13 == func_num_args())
        {
            $this->name              = func_get_arg(0);
            $this->parentPath        = func_get_arg(1);
            $this->checksum          = func_get_arg(2);
            $this->contentAccessible = func_get_arg(3);
            $this->contentToken      = func_get_arg(4);
            $this->deleted           = func_get_arg(5);
            $this->extension         = func_get_arg(6);
            $this->size              = func_get_arg(7);
            $this->systemAttributes  = func_get_arg(8);
            $this->version           = func_get_arg(9);
            $this->versionCreated    = func_get_arg(10);
            $this->viewUid           = func_get_arg(11);
            $this->uri               = func_get_arg(12);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']              = $this->name;
        $json['parentPath']        = $this->parentPath;
        $json['checksum']          = $this->checksum;
        $json['contentAccessible'] = $this->contentAccessible;
        $json['contentToken']      = $this->contentToken;
        $json['deleted']           = $this->deleted;
        $json['extension']         = $this->extension;
        $json['size']              = $this->size;
        $json['systemAttributes']  = $this->systemAttributes;
        $json['version']           = $this->version;
        $json['versionCreated']    = $this->versionCreated;
        $json['viewUid']           = $this->viewUid;
        $json['uri']               = $this->uri;

        return $json;
    }
}