<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsTel implements JsonSerializable {
    /**
     * Type of telephone number, e.g. home, mobile, etc
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * When combined with 'type', provides a unique identifier for the entry
     * @required
     * @var integer $indx public property
     */
    public $indx;

    /**
     * Telephone number
     * @required
     * @var string $number public property
     */
    public $number;

    /**
     * When sorting, lower numbers indicate a higher preference
     * @required
     * @var string $preference public property
     */
    public $preference;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $type         Initialization value for the property $this->type      
     * @param   integer           $indx         Initialization value for the property $this->indx      
     * @param   string            $number       Initialization value for the property $this->number    
     * @param   string            $preference   Initialization value for the property $this->preference
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->type       = func_get_arg(0);
            $this->indx       = func_get_arg(1);
            $this->number     = func_get_arg(2);
            $this->preference = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']       = $this->type;
        $json['indx']       = $this->indx;
        $json['number']     = $this->number;
        $json['preference'] = $this->preference;

        return $json;
    }
}