<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsAddress implements JsonSerializable {
    /**
     * Type of address, e.g. home, business, etc
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * When combined with 'type', provides a unique identifier for the entry
     * @required
     * @var integer $indx public property
     */
    public $indx;

    /**
     * For sorting. Lower numbers indicate a higher preference
     * @required
     * @var string $preference public property
     */
    public $preference;

    /**
     * @todo Write general description for this property
     * @var string $pobox public property
     */
    public $pobox;

    /**
     * @todo Write general description for this property
     * @var string $street public property
     */
    public $street;

    /**
     * @todo Write general description for this property
     * @var string $city public property
     */
    public $city;

    /**
     * @todo Write general description for this property
     * @var string $zipcode public property
     */
    public $zipcode;

    /**
     * @todo Write general description for this property
     * @var string $country public property
     */
    public $country;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $type         Initialization value for the property $this->type      
     * @param   integer           $indx         Initialization value for the property $this->indx      
     * @param   string            $preference   Initialization value for the property $this->preference
     * @param   string            $pobox        Initialization value for the property $this->pobox     
     * @param   string            $street       Initialization value for the property $this->street    
     * @param   string            $city         Initialization value for the property $this->city      
     * @param   string            $zipcode      Initialization value for the property $this->zipcode   
     * @param   string            $country      Initialization value for the property $this->country   
     */
    public function __construct()
    {
        if(8 == func_num_args())
        {
            $this->type       = func_get_arg(0);
            $this->indx       = func_get_arg(1);
            $this->preference = func_get_arg(2);
            $this->pobox      = func_get_arg(3);
            $this->street     = func_get_arg(4);
            $this->city       = func_get_arg(5);
            $this->zipcode    = func_get_arg(6);
            $this->country    = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']       = $this->type;
        $json['indx']       = $this->indx;
        $json['preference'] = $this->preference;
        $json['pobox']      = $this->pobox;
        $json['street']     = $this->street;
        $json['city']       = $this->city;
        $json['zipcode']    = $this->zipcode;
        $json['country']    = $this->country;

        return $json;
    }
}