<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Contacts implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var ContactsResponse $contactsResponse public property
     */
    public $contactsResponse;

    /**
     * Constructor to set initial or default values of member properties
     * @param   ContactsResponse   $contactsResponse   Initialization value for the property $this->contactsResponse
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->contactsResponse = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['contactsResponse'] = $this->contactsResponse;

        return $json;
    }
}