<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsContacts implements JsonSerializable {
    /**
     * Number of contacts
     * @required
     * @var integer $itemcount public property
     */
    public $itemcount;

    /**
     * Array of contacts
     * @required
     * @var Contact[] $contact public property
     */
    public $contact;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $itemcount   Initialization value for the property $this->itemcount
     * @param   array             $contact     Initialization value for the property $this->contact  
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->itemcount = func_get_arg(0);
            $this->contact   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['itemcount'] = $this->itemcount;
        $json['contact']   = $this->contact;

        return $json;
    }
}