<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsAddrbook implements JsonSerializable {
    /**
     * Timestamp of latest update
     * @required
     * @var string $updated public property
     */
    public $updated;

    /**
     * @todo Write general description for this property
     * @required
     * @var ContactsContacts $contacts public property
     */
    public $contacts;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $updated    Initialization value for the property $this->updated 
     * @param   ContactsContacts   $contacts   Initialization value for the property $this->contacts
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->updated  = func_get_arg(0);
            $this->contacts = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['updated']  = $this->updated;
        $json['contacts'] = $this->contacts;

        return $json;
    }
}