<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsAccount implements JsonSerializable {
    /**
     * Unique identifier for the current user
     * @required
     * @var string $userid public property
     */
    public $userid;

    /**
     * @todo Write general description for this property
     * @required
     * @var ContactsAddrbook $addrbook public property
     */
    public $addrbook;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $userid     Initialization value for the property $this->userid  
     * @param   ContactsAddrbook   $addrbook   Initialization value for the property $this->addrbook
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->userid   = func_get_arg(0);
            $this->addrbook = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['userid']   = $this->userid;
        $json['addrbook'] = $this->addrbook;

        return $json;
    }
}