<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Contact implements JsonSerializable {
    /**
     * Contact's given name
     * @var string $firstname public property
     */
    public $firstname;

    /**
     * Contact's surname
     * @var string $lastname public property
     */
    public $lastname;

    /**
     * Origin of the contact
     * @var string $source public property
     */
    public $source;

    /**
     * Arbitrary text associated with this contact
     * @var string $note public property
     */
    public $note;

    /**
     * Timestamp the contact was created
     * @var string $created public property
     */
    public $created;

    /**
     * Timestamp the contact was last updated
     * @var string $modified public property
     */
    public $modified;

    /**
     * Marked true for emergency contacts
     * @var bool $incaseofemergency public property
     */
    public $incaseofemergency;

    /**
     * Marked true for favorite contacts
     * @var bool $favorite public property
     */
    public $favorite;

    /**
     * List of contact's telephone numbers
     * @var ContactsTel[] $tel public property
     */
    public $tel;

    /**
     * List of contact's email addresses
     * @var ContactsEmail[] $email public property
     */
    public $email;

    /**
     * List of contact's addresses
     * @var ContactsAddress[] $address public property
     */
    public $address;

    /**
     * List of contact's IM addresses
     * @var ContactsIm[] $im public property
     */
    public $im;

    /**
     * @todo Write general description for this property
     * @var string $dedupe public property
     */
    public $dedupe;

    /**
     * Contact version.  This number increases when the contact is updated
     * @var integer $version public property
     */
    public $version;

    /**
     * Unique identifier for this contact
     * @var string $id public property
     */
    public $id;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $firstname           Initialization value for the property $this->firstname        
     * @param   string            $lastname            Initialization value for the property $this->lastname         
     * @param   string            $source              Initialization value for the property $this->source           
     * @param   string            $note                Initialization value for the property $this->note             
     * @param   string            $created             Initialization value for the property $this->created          
     * @param   string            $modified            Initialization value for the property $this->modified         
     * @param   bool              $incaseofemergency   Initialization value for the property $this->incaseofemergency
     * @param   bool              $favorite            Initialization value for the property $this->favorite         
     * @param   array             $tel                 Initialization value for the property $this->tel              
     * @param   array             $email               Initialization value for the property $this->email            
     * @param   array             $address             Initialization value for the property $this->address          
     * @param   array             $im                  Initialization value for the property $this->im               
     * @param   string            $dedupe              Initialization value for the property $this->dedupe           
     * @param   integer           $version             Initialization value for the property $this->version          
     * @param   string            $id                  Initialization value for the property $this->id               
     */
    public function __construct()
    {
        if(15 == func_num_args())
        {
            $this->firstname         = func_get_arg(0);
            $this->lastname          = func_get_arg(1);
            $this->source            = func_get_arg(2);
            $this->note              = func_get_arg(3);
            $this->created           = func_get_arg(4);
            $this->modified          = func_get_arg(5);
            $this->incaseofemergency = func_get_arg(6);
            $this->favorite          = func_get_arg(7);
            $this->tel               = func_get_arg(8);
            $this->email             = func_get_arg(9);
            $this->address           = func_get_arg(10);
            $this->im                = func_get_arg(11);
            $this->dedupe            = func_get_arg(12);
            $this->version           = func_get_arg(13);
            $this->id                = func_get_arg(14);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['firstname']         = $this->firstname;
        $json['lastname']          = $this->lastname;
        $json['source']            = $this->source;
        $json['note']              = $this->note;
        $json['created']           = $this->created;
        $json['modified']          = $this->modified;
        $json['incaseofemergency'] = $this->incaseofemergency;
        $json['favorite']          = $this->favorite;
        $json['tel']               = $this->tel;
        $json['email']             = $this->email;
        $json['address']           = $this->address;
        $json['im']                = $this->im;
        $json['dedupe']            = $this->dedupe;
        $json['version']           = $this->version;
        $json['id']                = $this->id;

        return $json;
    }
}