<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var ContactsAccount $account public property
     */
    public $account;

    /**
     * Constructor to set initial or default values of member properties
     * @param   ContactsAccount   $account   Initialization value for the property $this->account
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->account = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['account'] = $this->account;

        return $json;
    }
}