<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactsIm implements JsonSerializable {
    /**
     * Type of address, e.g. home, business, etc
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * IM contact string
     * @required
     * @var string $address public property
     */
    public $address;

    /**
     * For sorting. Lower numbers indicate a higher preference
     * @required
     * @var string $preference public property
     */
    public $preference;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $type         Initialization value for the property $this->type      
     * @param   string            $address      Initialization value for the property $this->address   
     * @param   string            $preference   Initialization value for the property $this->preference
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->type       = func_get_arg(0);
            $this->address    = func_get_arg(1);
            $this->preference = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']       = $this->type;
        $json['address']    = $this->address;
        $json['preference'] = $this->preference;

        return $json;
    }
}