<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DeletedList implements JsonSerializable {
    /**
     * An array of deleted file and folder paths.
     * @required
     * @var array $path public property
     */
    public $path;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $path   Initialization value for the property $this->path
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->path = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['path'] = $this->path;

        return $json;
    }
}