<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class FolderRequest implements JsonSerializable {
    /**
     * Folder name to be created.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Path where the folder has to be created.
     * @required
     * @var string $path public property
     */
    public $path;

    /**
     * Specifies what happens if a folder of the same name exists at the target path. Set to 'overwrite' to overwrite the existing folder. Set to 'modify' to treat the new folder as a modification of the old folder. If the 'override' parameter is not set, the following algorithm is applied if the existing folder has a 'deleted' attribute set to 'true', the folder is overwritten; if the old folder's 'deleted' attribute is false or not set, the folder is modified.
     * @required
     * @var string $override public property
     */
    public $override;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name       Initialization value for the property $this->name    
     * @param   string            $path       Initialization value for the property $this->path    
     * @param   string            $override   Initialization value for the property $this->override
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->name     = func_get_arg(0);
            $this->path     = func_get_arg(1);
            $this->override = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']     = $this->name;
        $json['path']     = $this->path;
        $json['override'] = $this->override;

        return $json;
    }
}