<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LinkResponse implements JsonSerializable {
    /**
     * The link identifier.
     * @required
     * @var string $rel public property
     */
    public $rel;

    /**
     * The URI of the link.
     * @required
     * @var string $link public property
     */
    public $link;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $rel    Initialization value for the property $this->rel 
     * @param   string            $link   Initialization value for the property $this->link
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->rel  = func_get_arg(0);
            $this->link = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['rel']  = $this->rel;
        $json['link'] = $this->link;

        return $json;
    }
}