<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MetadataUpdateRequest implements JsonSerializable {
    /**
     * The name of the system attribute to be updated
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The value of the system attribute
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * The URI to the file which needs to be updated
     * @required
     * @var string $uri public property
     */
    public $uri;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name    Initialization value for the property $this->name 
     * @param   string            $value   Initialization value for the property $this->value
     * @param   string            $uri     Initialization value for the property $this->uri  
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->name  = func_get_arg(0);
            $this->value = func_get_arg(1);
            $this->uri   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']  = $this->name;
        $json['value'] = $this->value;
        $json['uri']   = $this->uri;

        return $json;
    }
}