<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PlaylistBase implements JsonSerializable {
    /**
     * The name of the playlist
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The type of the playlist. Can be one of 'image', 'music', 'video' or 'image-video'
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name   Initialization value for the property $this->name
     * @param   string            $type   Initialization value for the property $this->type
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->name = func_get_arg(0);
            $this->type = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name'] = $this->name;
        $json['type'] = $this->type;

        return $json;
    }
}