<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Playlist implements JsonSerializable {
    /**
     * The uid of the playlist
     * @required
     * @var string $uid public property
     */
    public $uid;

    /**
     * The name of the playlist
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * The type of playlist
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Regex pattern for playlist
     * @required
     * @var string $mimeTypeRegex public property
     */
    public $mimeTypeRegex;

    /**
     * Timestamp for creation date of playlist
     * @required
     * @var string $creationDate public property
     */
    public $creationDate;

    /**
     * Timestamp for last modified date of playlist
     * @required
     * @var string $lastModifiedDate public property
     */
    public $lastModifiedDate;

    /**
     * Unique identifier of the resource
     * @required
     * @var string $uri public property
     */
    public $uri;

    /**
     * Array of paths
     * @var array $paths public property
     */
    public $paths;

    /**
     * Array of shareAssociation
     * @var ShareAssociation[] $shareAssociation public property
     */
    public $shareAssociation;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $uid                Initialization value for the property $this->uid             
     * @param   string            $name               Initialization value for the property $this->name            
     * @param   string            $type               Initialization value for the property $this->type            
     * @param   string            $mimeTypeRegex      Initialization value for the property $this->mimeTypeRegex   
     * @param   string            $creationDate       Initialization value for the property $this->creationDate    
     * @param   string            $lastModifiedDate   Initialization value for the property $this->lastModifiedDate
     * @param   string            $uri                Initialization value for the property $this->uri             
     * @param   array             $paths              Initialization value for the property $this->paths           
     * @param   array             $shareAssociation   Initialization value for the property $this->shareAssociation
     */
    public function __construct()
    {
        if(9 == func_num_args())
        {
            $this->uid              = func_get_arg(0);
            $this->name             = func_get_arg(1);
            $this->type             = func_get_arg(2);
            $this->mimeTypeRegex    = func_get_arg(3);
            $this->creationDate     = func_get_arg(4);
            $this->lastModifiedDate = func_get_arg(5);
            $this->uri              = func_get_arg(6);
            $this->paths            = func_get_arg(7);
            $this->shareAssociation = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['uid']              = $this->uid;
        $json['name']             = $this->name;
        $json['type']             = $this->type;
        $json['mimeTypeRegex']    = $this->mimeTypeRegex;
        $json['creationDate']     = $this->creationDate;
        $json['lastModifiedDate'] = $this->lastModifiedDate;
        $json['uri']              = $this->uri;
        $json['paths']            = $this->paths;
        $json['shareAssociation'] = $this->shareAssociation;

        return $json;
    }
}