<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PlaylistAddResponse implements JsonSerializable {
    /**
     * List of paths
     * @required
     * @var array $paths public property
     */
    public $paths;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $paths   Initialization value for the property $this->paths
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->paths = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['paths'] = $this->paths;

        return $json;
    }
}