<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PlaylistRequest implements JsonSerializable {
    /**
     * Name of the playlist.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * An array of paths to items.
     * @required
     * @var array $paths public property
     */
    public $paths;

    /**
     * The type of the playlist. Can be one of 'image', 'music', 'video' or 'image-video'
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name    Initialization value for the property $this->name 
     * @param   array             $paths   Initialization value for the property $this->paths
     * @param   string            $type    Initialization value for the property $this->type 
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->name  = func_get_arg(0);
            $this->paths = func_get_arg(1);
            $this->type  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']  = $this->name;
        $json['paths'] = $this->paths;
        $json['type']  = $this->type;

        return $json;
    }
}