<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PlaylistItem implements JsonSerializable {
    /**
     * Name of the file
     * @required
     * @var string $filename public property
     */
    public $filename;

    /**
     * Path of the file
     * @required
     * @var string $path public property
     */
    public $path;

    /**
     * Type of content
     * @required
     * @var string $mimeType public property
     */
    public $mimeType;

    /**
     * Size of the item
     * @required
     * @var integer $size public property
     */
    public $size;

    /**
     * Timestamp of version created date
     * @required
     * @var string $versionCreated public property
     */
    public $versionCreated;

    /**
     * @todo Write general description for this property
     * @required
     * @var PlaylistItem $fileAttribute public property
     */
    public $fileAttribute;

    /**
     * Unique token for content
     * @required
     * @var string $contentToken public property
     */
    public $contentToken;

    /**
     * Checksum detail
     * @required
     * @var string $checksum public property
     */
    public $checksum;

    /**
     * Show accessibility of the content
     * @required
     * @var bool $contentAccessible public property
     */
    public $contentAccessible;

    /**
     * File extension
     * @required
     * @var string $extension public property
     */
    public $extension;

    /**
     * @todo Write general description for this property
     * @required
     * @var object $tags public property
     */
    public $tags;

    /**
     * Unique identifier of the resource
     * @required
     * @var string $uri public property
     */
    public $uri;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $filename            Initialization value for the property $this->filename         
     * @param   string            $path                Initialization value for the property $this->path             
     * @param   string            $mimeType            Initialization value for the property $this->mimeType         
     * @param   integer           $size                Initialization value for the property $this->size             
     * @param   string            $versionCreated      Initialization value for the property $this->versionCreated   
     * @param   PlaylistItem      $fileAttribute       Initialization value for the property $this->fileAttribute    
     * @param   string            $contentToken        Initialization value for the property $this->contentToken     
     * @param   string            $checksum            Initialization value for the property $this->checksum         
     * @param   bool              $contentAccessible   Initialization value for the property $this->contentAccessible
     * @param   string            $extension           Initialization value for the property $this->extension        
     * @param   object            $tags                Initialization value for the property $this->tags             
     * @param   string            $uri                 Initialization value for the property $this->uri              
     */
    public function __construct()
    {
        if(12 == func_num_args())
        {
            $this->filename          = func_get_arg(0);
            $this->path              = func_get_arg(1);
            $this->mimeType          = func_get_arg(2);
            $this->size              = func_get_arg(3);
            $this->versionCreated    = func_get_arg(4);
            $this->fileAttribute     = func_get_arg(5);
            $this->contentToken      = func_get_arg(6);
            $this->checksum          = func_get_arg(7);
            $this->contentAccessible = func_get_arg(8);
            $this->extension         = func_get_arg(9);
            $this->tags              = func_get_arg(10);
            $this->uri               = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['filename']          = $this->filename;
        $json['path']              = $this->path;
        $json['mimeType']          = $this->mimeType;
        $json['size']              = $this->size;
        $json['versionCreated']    = $this->versionCreated;
        $json['fileAttribute']     = $this->fileAttribute;
        $json['contentToken']      = $this->contentToken;
        $json['checksum']          = $this->checksum;
        $json['contentAccessible'] = $this->contentAccessible;
        $json['extension']         = $this->extension;
        $json['tags']              = $this->tags;
        $json['uri']               = $this->uri;

        return $json;
    }
}