<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ResourceRequest implements JsonSerializable {
    /**
     * Name of the resource.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Location of the resource. This is a URI value obtained from a fullview, metadata, or playlist response
     * @required
     * @var string $location public property
     */
    public $location;

    /**
     * Type of the resource: file/folder/playlist
     * @var string $type public property
     */
    public $type;

    /**
     * (Optional) subtype of the resource: image/video/audio.  Used to aid playback of the file when viewed in a browser
     * @var string $subType public property
     */
    public $subType;

    /**
     * Size of the resource. Mandatory in case of file share only.
     * @var integer $size public property
     */
    public $size;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name       Initialization value for the property $this->name    
     * @param   string            $location   Initialization value for the property $this->location
     * @param   string            $type       Initialization value for the property $this->type    
     * @param   string            $subType    Initialization value for the property $this->subType 
     * @param   integer           $size       Initialization value for the property $this->size    
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->name     = func_get_arg(0);
            $this->location = func_get_arg(1);
            $this->type     = func_get_arg(2);
            $this->subType  = func_get_arg(3);
            $this->size     = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']     = $this->name;
        $json['location'] = $this->location;
        $json['type']     = $this->type;
        $json['subType']  = $this->subType;
        $json['size']     = $this->size;

        return $json;
    }
}