<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ResourceResponse implements JsonSerializable {
    /**
     * Name of the resource.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Type of the resource.
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * The resource identifier.
     * @var string $uid public property
     */
    public $uid;

    /**
     * SubType of the resource.
     * @var string $subType public property
     */
    public $subType;

    /**
     * Location of the resource.
     * @var string $location public property
     */
    public $location;

    /**
     * Size of the resource.
     * @var integer $size public property
     */
    public $size;

    /**
     * Id of the resource.
     * @var string $resourceId public property
     */
    public $resourceId;

    /**
     * ContentToken of the resource.
     * @var string $contentToken public property
     */
    public $contentToken;

    /**
     * Checksum of the resource.
     * @var string $checksum public property
     */
    public $checksum;

    /**
     * LastModifiedDate of the resource.
     * @var string $lastModifiedDate public property
     */
    public $lastModifiedDate;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name               Initialization value for the property $this->name            
     * @param   string            $type               Initialization value for the property $this->type            
     * @param   string            $uid                Initialization value for the property $this->uid             
     * @param   string            $subType            Initialization value for the property $this->subType         
     * @param   string            $location           Initialization value for the property $this->location        
     * @param   integer           $size               Initialization value for the property $this->size            
     * @param   string            $resourceId         Initialization value for the property $this->resourceId      
     * @param   string            $contentToken       Initialization value for the property $this->contentToken    
     * @param   string            $checksum           Initialization value for the property $this->checksum        
     * @param   string            $lastModifiedDate   Initialization value for the property $this->lastModifiedDate
     */
    public function __construct()
    {
        if(10 == func_num_args())
        {
            $this->name             = func_get_arg(0);
            $this->type             = func_get_arg(1);
            $this->uid              = func_get_arg(2);
            $this->subType          = func_get_arg(3);
            $this->location         = func_get_arg(4);
            $this->size             = func_get_arg(5);
            $this->resourceId       = func_get_arg(6);
            $this->contentToken     = func_get_arg(7);
            $this->checksum         = func_get_arg(8);
            $this->lastModifiedDate = func_get_arg(9);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']             = $this->name;
        $json['type']             = $this->type;
        $json['uid']              = $this->uid;
        $json['subType']          = $this->subType;
        $json['location']         = $this->location;
        $json['size']             = $this->size;
        $json['resourceId']       = $this->resourceId;
        $json['contentToken']     = $this->contentToken;
        $json['checksum']         = $this->checksum;
        $json['lastModifiedDate'] = $this->lastModifiedDate;

        return $json;
    }
}