<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ShareResponseList implements JsonSerializable {
    /**
     * The total number of shares
     * @var integer $count public property
     */
    public $count;

    /**
     * @todo Write general description for this property
     * @var LinkResponse[] $links public property
     */
    public $links;

    /**
     * @todo Write general description for this property
     * @var ShareResponse[] $share public property
     */
    public $share;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $count   Initialization value for the property $this->count
     * @param   array             $links   Initialization value for the property $this->links
     * @param   array             $share   Initialization value for the property $this->share
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->count = func_get_arg(0);
            $this->links = func_get_arg(1);
            $this->share = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['count'] = $this->count;
        $json['links'] = $this->links;
        $json['share'] = $this->share;

        return $json;
    }
}