<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ShareAssociation implements JsonSerializable {
    /**
     * Unique id
     * @required
     * @var string $uid public property
     */
    public $uid;

    /**
     * Visibility of share association
     * @required
     * @var string $visibility public property
     */
    public $visibility;

    /**
     * Name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Type of share association
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $uid          Initialization value for the property $this->uid       
     * @param   string            $visibility   Initialization value for the property $this->visibility
     * @param   string            $name         Initialization value for the property $this->name      
     * @param   string            $type         Initialization value for the property $this->type      
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->uid        = func_get_arg(0);
            $this->visibility = func_get_arg(1);
            $this->name       = func_get_arg(2);
            $this->type       = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['uid']        = $this->uid;
        $json['visibility'] = $this->visibility;
        $json['name']       = $this->name;
        $json['type']       = $this->type;

        return $json;
    }
}