<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ShareResponse implements JsonSerializable {
    /**
     * The name of the share.
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var LinkResponse[] $links public property
     */
    public $links;

    /**
     * The resource identifier.
     * @var string $uid public property
     */
    public $uid;

    /**
     * The owner of the share
     * @var object $owner public property
     */
    public $owner;

    /**
     * The sharer of the share
     * @var object $sharer public property
     */
    public $sharer;

    /**
     * The total count of shared resources.
     * @var integer $totalResourceCount public property
     */
    public $totalResourceCount;

    /**
     * The time to live of the share in seconds.
     * @var integer $expiresIn public property
     */
    public $expiresIn;

    /**
     * Expiration date on the share.
     * @var string $expirationDate public property
     */
    public $expirationDate;

    /**
     * The date and time the share was created.
     * @var string $creationDate public property
     */
    public $creationDate;

    /**
     * The date and time the share was last modified from the perspective of the owner.
     * @var string $lastModifiedDate public property
     */
    public $lastModifiedDate;

    /**
     * The date and time the share was last modified from the perspective of a member.
     * @var string $inboundLastModifiedDate public property
     */
    public $inboundLastModifiedDate;

    /**
     * The invite key of a public share.
     * @var string $publicInviteKey public property
     */
    public $publicInviteKey;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name                      Initialization value for the property $this->name                   
     * @param   array             $links                     Initialization value for the property $this->links                  
     * @param   string            $uid                       Initialization value for the property $this->uid                    
     * @param   object            $owner                     Initialization value for the property $this->owner                  
     * @param   object            $sharer                    Initialization value for the property $this->sharer                 
     * @param   integer           $totalResourceCount        Initialization value for the property $this->totalResourceCount     
     * @param   integer           $expiresIn                 Initialization value for the property $this->expiresIn              
     * @param   string            $expirationDate            Initialization value for the property $this->expirationDate         
     * @param   string            $creationDate              Initialization value for the property $this->creationDate           
     * @param   string            $lastModifiedDate          Initialization value for the property $this->lastModifiedDate       
     * @param   string            $inboundLastModifiedDate   Initialization value for the property $this->inboundLastModifiedDate
     * @param   string            $publicInviteKey           Initialization value for the property $this->publicInviteKey        
     */
    public function __construct()
    {
        if(12 == func_num_args())
        {
            $this->name                    = func_get_arg(0);
            $this->links                   = func_get_arg(1);
            $this->uid                     = func_get_arg(2);
            $this->owner                   = func_get_arg(3);
            $this->sharer                  = func_get_arg(4);
            $this->totalResourceCount      = func_get_arg(5);
            $this->expiresIn               = func_get_arg(6);
            $this->expirationDate          = func_get_arg(7);
            $this->creationDate            = func_get_arg(8);
            $this->lastModifiedDate        = func_get_arg(9);
            $this->inboundLastModifiedDate = func_get_arg(10);
            $this->publicInviteKey         = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']                    = $this->name;
        $json['links']                   = $this->links;
        $json['uid']                     = $this->uid;
        $json['owner']                   = $this->owner;
        $json['sharer']                  = $this->sharer;
        $json['totalResourceCount']      = $this->totalResourceCount;
        $json['expiresIn']               = $this->expiresIn;
        $json['expirationDate']          = $this->expirationDate;
        $json['creationDate']            = $this->creationDate;
        $json['lastModifiedDate']        = $this->lastModifiedDate;
        $json['inboundLastModifiedDate'] = $this->inboundLastModifiedDate;
        $json['publicInviteKey']         = $this->publicInviteKey;

        return $json;
    }
}