<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TagsResponse implements JsonSerializable {
    /**
     * A set of Tags
     * @required
     * @maps Tags
     * @var string $tags public property
     */
    public $tags;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $tags   Initialization value for the property $this->tags
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->tags = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Tags'] = $this->tags;

        return $json;
    }
}