<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TrashData implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var BaseFileMetadata[] $file public property
     */
    public $file;

    /**
     * @todo Write general description for this property
     * @var BaseFolderMetadata[] $folder public property
     */
    public $folder;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $file     Initialization value for the property $this->file  
     * @param   array             $folder   Initialization value for the property $this->folder
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->file   = func_get_arg(0);
            $this->folder = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['file']   = $this->file;
        $json['folder'] = $this->folder;

        return $json;
    }
}