<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class UpdateTagsRequest implements JsonSerializable {
    /**
     * URI of the resource. This is a URI value obtained from a fullview or metadata response
     * @required
     * @var string $uri public property
     */
    public $uri;

    /**
     * A set of Tags
     * @required
     * @maps Tags
     * @var string $tags public property
     */
    public $tags;

    /**
     * If 'true', creates a new version of the file or folder. Defaults to 'false'.
     * @var bool $createVersion public property
     */
    public $createVersion;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $uri             Initialization value for the property $this->uri          
     * @param   string            $tags            Initialization value for the property $this->tags         
     * @param   bool              $createVersion   Initialization value for the property $this->createVersion
     */
    public function __construct()
    {
        switch(func_num_args())      
        {
            case 3:
                $this->uri           = func_get_arg(0);
                $this->tags          = func_get_arg(1);
                $this->createVersion = func_get_arg(2);
                break;

            default:
                $this->createVersion = FALSE;
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['uri']           = $this->uri;
        $json['Tags']          = $this->tags;
        $json['createVersion'] = $this->createVersion;

        return $json;
    }
}