<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Uploadurls implements JsonSerializable {
    /**
     * The upload url with the uploadid to upload the binary content of the file.
     * @required
     * @var string $uploadurl public property
     */
    public $uploadurl;

    /**
     * The commit url to create the file after binary content is uploaded in chunks.
     * @var string $commiturl public property
     */
    public $commiturl;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $uploadurl   Initialization value for the property $this->uploadurl
     * @param   string            $commiturl   Initialization value for the property $this->commiturl
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->uploadurl = func_get_arg(0);
            $this->commiturl = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['uploadurl'] = $this->uploadurl;
        $json['commiturl'] = $this->commiturl;

        return $json;
    }
}