<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Usage implements JsonSerializable {
    /**
     * Total quota space available to the user on the cloud in bytes
     * @required
     * @var integer $quota public property
     */
    public $quota;

    /**
     * Total quota space used in bytes
     * @required
     * @var integer $quotaUsed public property
     */
    public $quotaUsed;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $quota       Initialization value for the property $this->quota    
     * @param   integer           $quotaUsed   Initialization value for the property $this->quotaUsed
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->quota     = func_get_arg(0);
            $this->quotaUsed = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['quota']     = $this->quota;
        $json['quotaUsed'] = $this->quotaUsed;

        return $json;
    }
}