<?php 
/*
 * PersonalCloudStorageAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/13/2016
 */

namespace PersonalCloudStorageAPIsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ViewUid implements JsonSerializable {
    /**
     * Shared Type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Type of view
     * @required
     * @var string $viewType public property
     */
    public $viewType;

    /**
     * Unique id of view
     * @required
     * @var string $uid public property
     */
    public $uid;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $type       Initialization value for the property $this->type    
     * @param   string            $viewType   Initialization value for the property $this->viewType
     * @param   string            $uid        Initialization value for the property $this->uid     
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->type     = func_get_arg(0);
            $this->viewType = func_get_arg(1);
            $this->uid      = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']     = $this->type;
        $json['viewType'] = $this->viewType;
        $json['uid']      = $this->uid;

        return $json;
    }
}